" inspired from https://dougblack.io/words/a-good-vimrc.html
" and https://drivy.engineering/setting-up-vim-for-react/

" PLUGINS
call plug#begin('~/.vim/plugged')

Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'

Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'jiangmiao/auto-pairs'
Plug 'agarrharr/consolation-vim'
Plug 'vim-airline/vim-airline'
Plug 'mileszs/ack.vim'

Plug 'tomasiser/vim-code-dark'

Plug 'ternjs/tern_for_vim', {'do': 'npm i'}
Plug 'mattn/emmet-vim'
" Plug 'w0rp/ale'
Plug 'skywind3000/asyncrun.vim'
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
call plug#end()

colorscheme codedark 

" AUTOCOMPLETE
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" TABS & SPACES
syntax enable	" Enable syntax highlighting
set tabstop=2	" number of visual spaces per TAB
set softtabstop=2 " number of spaces in tab when editing
set shiftwidth=2
set expandtab 	" tabs are spaces

" UI CONFIG
set number 	" Enable line numbers
set relativenumber " Display relative line numbers (line numbers from current line)
set showcmd		" show last command in bottom bar
set cursorline    " highlight current line
filetype indent on    " load filetype-specific indent file
set wildmenu    " visual autocomplete for command menu
set lazyredraw    " redraw only when we need to
set showmatch   " highlight matching {[()]}

" SEARCHING
set incsearch   " search as characters are entered
set hlsearch    " highlight matches
set path+=**
set wildignore+=**/node_modules/**

"ack config
nnoremap <Leader>a :Ack!<Space>
let g:ackprg = 'ack -s -H --nogroup --column'

" FOLDING
set foldenable    " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10    " 10 nested fold max

" MOVEMENT
" move vertically by visual line 
nnoremap j gj
nnoremap k gk
" highlight last inserted text
nnoremap gV `[v`]   
" Navigate to previous and next buffer
:nnoremap <Tab> :bnext<CR>
:nnoremap <S-Tab> :bprevious<CR>

" LEADER SHORTCUTS
" jk is escape
inoremap jk <esc>

" Emmet config
let g:user_emmet_leader_key='<Tab>'
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
    \      'extends' : 'jsx',
    \  },
  \}

" vim-prettier
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
let g:prettier#exec_cmd_async = 1
let g:prettier#config#tab_width = 2
let g:prettier#config#print_width = 80

" NERDTree config
let NERDTreeShowHidden=1
" How can I open a NERDTree automatically when vim starts up if no files were specified?
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" How can I close vim if the only window left open is a NERDTree?
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" How can I map a specific key or shortcut to open NERDTree?
map <C-n> :NERDTreeToggle<CR>

" CtrlP config (fuzzy file finder)
let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
let g:ctrlp_show_hidden=1

" consation-vim config
nnoremap <leader>c :Consolate<cr>
