" inspired from https://dougblack.io/words/a-good-vimrc.html

" PLUGINS
call plug#begin('~/.vim/plugged')

Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'jiangmiao/auto-pairs'

Plug 'tomasiser/vim-code-dark'

Plug 'mattn/emmet-vim'
Plug 'w0rp/ale'
Plug 'skywind3000/asyncrun.vim'
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
call plug#end()

colorscheme codedark 

" TABS & SPACES
syntax enable	" Enable syntax highlighting
set tabstop=2	" number of visual spaces per TAB
set softtabstop=2 " number of spaces in tab when editing
set expandtab 	" tabs are spaces

" UI CONFIG
set number 	" Enable line numbers
set relativenumber " Display relative line numbers (line numbers from current line)
set showcmd		" show last command in bottom bar
set cursorline    " highlight current line
filetype indent on    " load filetype-specific indent file
set wildmenu    " visual autocomplete for command menu
set lazyredraw    " redraw only when we need to
set showmatch   " highlight matching {[()]}

" SEARCHING
set incsearch   " search as characters are entered
set hlsearch    " highlight matches
set path+=**
set wildignore+=**/node_modules/**

" FOLDING
set foldenable    " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10    " 10 nested fold max

" MOVEMENT
" move vertically by visual line 
nnoremap j gj
nnoremap k gk
" highlight last inserted text
nnoremap gV `[v`]   

" LEADER SHORTCUTS
" jk is escape
inoremap jk <esc>

" Emmet config
let g:user_emmet_leader_key='<Tab>'
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
    \      'extends' : 'jsx',
    \  },
  \}

" vim-prettier
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
let g:prettier#exec_cmd_async = 1

